# Generated by Django 4.0.6 on 2022-08-18 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist_user',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlister',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='watchlister', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
