# Generated by Django 4.1 on 2022-08-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_listing', to='auctions.listing'),
        ),
    ]
