# Generated by Django 4.1 on 2022-08-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bids_bid_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
