# Generated by Django 4.1 on 2022-08-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bids_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bid_listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.ManyToManyField(blank=True, related_name='current_bid', to='auctions.bids'),
        ),
    ]
