# Generated by Django 4.1 on 2022-08-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid_default',
            field=models.IntegerField(default=0),
        ),
    ]
